
debug: "yes"

input_dir: "SSGin"
#output_dir: "..\\..\\..\\..\\..\\..\\Software\\Websites\\PromptUniversity"
output_dir: "SSGout"
snippets_dir: "Snippets"

block_substitutions:
  - name: "Header"
    file: "Header.html"
  - name: "Footer"
    file: "Footer.html"

inline_substitutions:
  - name: "TURNSTILE_SITE_KEY"
#   text: "1x00000000000000000000AA"
    text: "0x4AAAAAADOIv861cSQRc0Ua"
